### ISSUE TITLE
JPEG image is not recognized at all by FastImage

### ISSUE THREAD

**Issue by Catalectic** [sdsykes/fastimage#54]
Hello,

We've been running into an issue where some images from Zara are not recognized at all by FastImage (1.7.0). Eg FastImage.type("http://static.zara.net/photos//2015/V/0/1/p/1639/075/067/2/w/1024/1639075067_2_1_1.jpg") => nil

But the image shows up correctly with ImageMagick identify: 1639075067_2_1_1.jpg JPEG 1024x1269 1024x1269+0+0 8-bit sRGB 201KB 0.000u 0:00.000

Any ideas what might be happening here? I didn't see anything strange in the returned headers (it's sent as an image/jpeg).

Thanks in advance, and thanks for your work on this gem!

**Comment by sdsykes** [comment]
Will look at this asap.

**Comment by sdsykes** [comment]
Ok, I have investigated this. It's the User-Agent string. FastImage is sending "Ruby" as the user agent. And static.zara.net is returning 404 (actually they seem to be using Akamai).

If you change the User-Agent to be, for instance, "Quby" instead of "Ruby", then the server returns the image ok.

Perhaps it's some kind of DOS mitigation, or just a war against ruby (who knows?)

But anyway, the only way around it is to supply another User-Agent string. 

Eg line 218:

    @http.request_get(@parsed_uri.request_uri, 'Accept-Encoding' => 'identity', 'User-Agent' => "Quby") do |res|

Possibly I could add a feature so you could specify the user agent, I can consider it.

For immediate relief, fork or just patch fastimage.

**Comment by Catalectic** [comment]
Thanks for the quick investigation and the pointer for fixing this!

I could work on a pull request if you would like this feature in and are open to contributions. Either way feel free to consider this issue closed :)

**Comment by sdsykes** [comment]
Actually my colleague just suggested we could change the user agent to "FastImage", which would be acceptable I think.
