### ISSUE TITLE
FastImage.size fails after remote HTTP request

### ISSUE THREAD

**Issue by mitchmeyer1** [sdsykes/fastimage#82]
My application layout uses FastImage to implement size data for js use on the front end.  It normally works but every time it fails when I reload the page after a remote HTTP request.  My page has a 'subscribe' field.  
The order is or events is:
1. load page which uses FastImage.size => success 
2. Do remote HTTP Post from that page => success
3. Reload page => FastImage.size cannot fetch image
4. Reload again => its fine

-Mitch

**Comment by mitchmeyer1** [comment]
Follow up - works in my live environments, but fails reliably when running local server

**Comment by sdsykes** [comment]
I'm suspecting that there is an issue with the local webserver. We've seen before that, using thin (for example) and trying to fetch images at the same time as the server is processing your request can fail because the server cannot do two things at once. Try WebBrick if you are using something else.

**Comment by sdsykes** [comment]
Closing, no further feedback.
