### ISSUE TITLE
warning: already initialized constant URI::DEFAULT_PARSER

### ISSUE THREAD

**Issue by yakimant** [sdsykes/fastimage#87]
Have this warning on 2.1.0, but not on 2.0.1, macOS, system ruby.

Full message:
```
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
```

**Comment by sdsykes** [comment]
This is actually a known issue. It's because of this commit https://github.com/sdsykes/fastimage/commit/31042836d44e6e7290d9e92d59d2c32bd7be3db4 which solves the URL underscore issue for versions of Ruby that have it. See here: http://stackoverflow.com/questions/5208851/i/41048816#41048816

There might be a workaround for avoiding the warning by temporarily changing the $VERBOSE setting, that's not a particularly nice thing in a gem though.

The ultimate answer is to use a more recent version of Ruby. macOS High Sierra ships with Ruby 2.3.3, so the issue will eventually go away for Mac users.

**Comment by yakimant** [comment]
Thanks, @sdsykes! I will use 2.0.1 for now.
